on:
  push:
    branches:
      - main
name: Prod - Build & Deploy
env:
  LOCATION: centralindia
  RESOURCE_GROUP: WorldTimelineARG
  CONTAINER_REGISTERY: worldtimelineacr
  APP_NAME: world-timeline-ui
  WEBAPP_NAME: worldtimelineui
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout GitHub Action
          uses: actions/checkout@master
          
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.PROD_AZURE_CREDENTIALS }}

        - name: Set default location
          run: |
            az configure --defaults location=${{ env.LOCATION }}
            az configure --defaults group=${{ env.RESOURCE_GROUP }}

        - name: Create .env
          run: |
            touch .env
            printf '${{ secrets.PROD_UI_ENV }}' > .env
        
        - name: Build & Push
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.CONTAINER_REGISTERY }}.azurecr.io
            username: ${{ secrets.PROD_AZURE_USERNAME }}
            password: ${{ secrets.PROD_AZURE_PASSWORD }}
        - run: |
            docker build . -t ${{ env.APP_NAME }}:1.0.${{ github.run_number }}
            docker tag ${{ env.APP_NAME }}:1.0.${{ github.run_number }} ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}
            docker push ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}

        - uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.WEBAPP_NAME }}
            images: ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}

        - name: logout
          run: |
            az logout
